<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-TelemetryProcessor-890ab0df-5934-4694-a952-260ee653c8a9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Cvp.Contracts\Cvp.Contracts.csproj" />
    <ProjectReference Include="..\..\Shared\Cvp.Common\Cvp.Common.csproj" />
  </ItemGroup>
</Project>
